export const SPOTIFY_CLIENT_ID = 'SPOTIFY_CLIENT_ID';
export const SPOTIFY_CLIENT_SECRET = 'SPOTIFY_CLIENT_SECRET';
export const SPOTIFY_API_URL = 'SPOTIFY_API_URL';
export const SPOTIFY_ACCESS_TOKEN_URL = 'SPOTIFY_ACCESS_TOKEN_URL';
